### ISSUE TITLE
expected succesfull input

### ISSUE THREAD

**Issue by bradfordcondon** [UofS-Pulse-Binfo/tripal_bibtex#3]
Hi Lacey,

```
 @ARTICLE{Sanderson2013-gy,
   title   = {Tripal v0000: a test bibtex file},
   author  = {Sanderson, Lacey-Anne and Ficklin, Stephen P and Cheng, Chun-Huai
              and Jung, Sook and Feltus, Frank A and Bett, Kirstin E and Main,
              Dorrie},
   journal = {Database},
   volume  =  {2013},
   number  =  {0},
   pages   = {bat075--bat075},
   year    =  {2013}
 }
```

is this the expected format?

The only regexp that matches with this file is the closing tag one...

**Comment by laceysanderson** [comment]
This was my test file:
```
@article{Sanderson2013,
abstract = {Tripal is an open-source freely available toolkit for construction of online genomic and genetic databases. It aims to facilitate development of community-driven biological websites by integrating the GMOD Chado database schema with Drupal, a popular website creation and content management software. Tripal provides a suite of tools for interaction with a Chado database and display of content therein. The tools are designed to be generic to support the various ways in which data may be stored in Chado. Previous releases of Tripal have supported organisms, genomic libraries, biological stocks, stock collections and genomic features, their alignments and annotations. Also, Tripal and its extension modules provided loaders for commonly used file formats such as FASTA, GFF, OBO, GAF, BLAST XML, KEGG heir files and InterProScan XML. Default generic templates were provided for common views of biological data, which could be customized using an open Application Programming Interface to change the way data are displayed. Here, we report additional tools and functionality that are part of release v1.1 of Tripal. These include (i) a new bulk loader that allows a site curator to import data stored in a custom tab delimited format; (ii) full support of every Chado table for Drupal Views (a powerful tool allowing site developers to construct novel displays and search pages); (iii) new modules including 'Feature Map', 'Genetic', 'Publication', 'Project', 'Contact' and the 'Natural Diversity' modules. Tutorials, mailing lists, download and set-up instructions, extension modules and other documentation can be found at the Tripal website located at http://tripal.info. DATABASE URL: http://tripal.info/.},
title = {Tripal v1.1: a standards-based toolkit for construction of online genetic and genomic databases.},
author = {Sanderson, LA and Ficklin, SP and Cheng, CH and Jung, S and Feltus, FA and Bett, KE and Main, D},
pages = {bat075},
url = {http://f1000.com/pubmed/ref/24163125},
year = {2013},
month = {oct},
journal = {Database (Oxford)},
volume = {2013},
doi = {10.1093/database/bat075},
pmid = {24163125}
}
```

It was supposed to handle tags spanning multiple lines as well although I see my test doesn't test that 😝. It looks like the issue is the indenting on yours which is much more readable. We'll have to update the regex to allow preceding white space.

**Comment by bradfordcondon** [comment]
the problem is my whitespace around the keys, yep.  Thanks!

**Comment by bradfordcondon** [comment]
Issues:

* whitespace around keys kills it
* ARTICLE kills it (wants article, or for the ARTICLE term to be loaded in...)

for what its worth this is the bibtex created by paperiple (i changed the "'s to braces manually) so ideally i'd add in support for that format since thats what im using typically.  unless theres a way to get bibtex from pubmed?  I didnt see it...

**Comment by bradfordcondon** [comment]
thanks for your test file, really helps a lot.

Would you be willing to turn on Travis-ci integration?  I'm adding unit tests via test suite...

**Comment by laceysanderson** [comment]
Definitely! I think I've turned Travis-CI on: 
![screen shot 2018-05-29 at 4 22 39 pm](https://user-images.githubusercontent.com/1566301/40688777-9a63d4ba-635c-11e8-8308-8c7170cd305b.png)
Is that what you needed?

Feel free to add separate issues for any bugs you find :-) <3 
Our BibTex was from F1000. Your `"` were a known limitation of my original regex that I didn't spend time on b/c I didn't need it. If you want to add support for that in -I'd be happy/grateful :-)

**Comment by bradfordcondon** [comment]
yeah!  when the PR is made it should trigger from then on.  Thanks lacey!  I definitely dont expect features that werent needed when you made the tool, thanks for giving me a great place to start.

**Comment by laceysanderson** [comment]
Hi @bradfordcondon, you can get bibtex export from the pubmed collection via http://www.bioinformatics.org/texmed/ which uses the pubmed API :-)

**Comment by bradfordcondon** [comment]
thanks!   I actually tried a search, saw no results, and gave up pretty fast.  maybe ill give it another shot.
