### ISSUE TITLE
Be more tolerant of whitespace.

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_bibtex#5]
Currently any whitespace at the beginning of a `tag = value` pair causes it to not be recognized as shown in @bradfordcondon example bibtext file: https://github.com/UofS-Pulse-Binfo/tripal_bibtex/blob/7.x-3.x/example/example.bib

We should be more tolerant especially since this makes the file Much more readable.

**Comment by bradfordcondon** [comment]
I was thinking about this: would it make sense to just split on `_=_ ` and trim the 0 key to remove whitespace?

**Comment by laceysanderson** [comment]
I think we're better off making the regex more tolerant. We could end up with issues if there is an `=` in the value: `tag = {lorem ipsum = latin nonsense}`

**Comment by laceysanderson** [comment]
Also solved in @spficklin PR
