### ISSUE TITLE
Support enclosing values in quotes OR curley braces

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_bibtex#9]
Apparently values can either be enclosed in {} or "", I only support {}. That said, there are a number of exporters that use the quote methods so we should consider this enhancement. Specifically, this would be of benefit to @bradfordcondon.

**Comment by spficklin** [comment]
So, I was testing loading a bibtex file into my new internal publication Tripal site and hit on this error.  So I fixed it for at least on example I was working on.

**Comment by laceysanderson** [comment]
Merged in @spficklin PR so now this works. Thanks again!
